repo_url: https://github.com/Requisitos-de-Software/2024.1-Serasa
repo_name: 2024.1-Serasa
site_name: Serasa Consulta CPF e Socore
nav: 
  - Home: index.md
  - Atas:
    - Reunião 1: atas/ata1.md
  - Planejamento:
      - Heatmap: planejamento/heatmap.md
theme:
  name: material
  logo: assets/serasa_logo_white.svg
  features:
    - navigation.tabs
  palette:
    - scheme : default
      primary: pink
      toggle:
        icon: material/toggle-switch
        name: Mudar o modo clar/escuro 
    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mudar o modo clar/escuro


