repo_url: https://github.com/Requisitos-de-Software/2024.1-Correios
repo_name: 2024.1-Correios
site_name: Correios
nav: 
  - Equipe: index.md
  - Apresentações:
    - Apresentação 01: Apresentações/Apresentação_01.md
  - Atas:
    - Reunião 1: atas/ata1.md
  - Pré-Rastreabilidade:
    - Rich Picture: pre-rastreabilidade/richpicture.md
    - Aplicativos Avaliados: pre-rastreabilidade/appsavaliados.md
  - Planejamento:
    - Aplicativo escolhido: planejamento/aplicativoEscolhido.md
    - Heatmap: planejamento/heatmap.md
    - Cronograma:  planejamento/cronograma.md
    - Termo de Uso: planejamento/termodeuso.md
    - Ferramentas: planejamento/ferramentas.md
theme:
  language: pt-BR
  name: material
  favicon: assets/correios_icon.svg
  logo: assets/correios.svg
  features:
    - navigation.tabs
  palette:
    - scheme : default
      primary: amber
      toggle:
        icon: material/toggle-switch
        name: Mudar o modo clar/escuro 

    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mudar o modo clar/escuro


