repo_url: https://github.com/Requisitos-de-Software/2024.1-Correios
repo_name: 2024.1-Correios
site_name: Correios
nav: 
  - Equipe: index.md
  - Apresentações:
    - Apresentação 01: Apresentações/Apresentação_01.md
    - Apresentação 02: Apresentações/Apresentação_02.md
    - Apresentação 03: Apresentações/Apresentação_03.md
    - Apresentação 04: Apresentações/Apresentação_04.md
  - Atas:
    - Reunião 1: atas/ata1.md
    - Reunião 2: atas/ata2.md
    - Reunião 3: atas/ata3.md
    - Reunião 4: atas/ata4.md
  - Pré-Rastreabilidade:
    - Rich Picture: pre-rastreabilidade/richpicture.md
    - Aplicativos Avaliados: pre-rastreabilidade/appsavaliados.md
  - Planejamento:
    - Aplicativo escolhido: planejamento/aplicativoEscolhido.md
    - Heatmap: planejamento/heatmap.md
    - Cronograma:  planejamento/cronograma.md
    - Termo de Uso: planejamento/termodeuso.md
    - Ferramentas: planejamento/ferramentas.md
  - Elicitação:
    - Perfil de Usuário: elicitacao/perfil_de_usuario/perfil_de_usuario.md
    - Personas: elicitacao/personas.md
    - Técnicas:
      - Análise Documental: elicitacao/tecnicas/analise-documental.md
      - Brainstorming: elicitacao/tecnicas/brainstorming.md
      - Observação: elicitacao/tecnicas/observacao.md
      - Questionário: elicitacao/tecnicas/questionario.md
    - Priorização: 
      - $100: priorizacao/tecnicas/$100.md
      - First Things First: priorizacao/tecnicas/firstThingsFirst.md
      - In Or Out: priorizacao/tecnicas/inorout.md
    - Requisitos Elicitados: "elicitacao/requisitos_elicitados.md"
  - Modelagem:
    - Cenários: modelagem/cenarios.md
    - Casos de Uso: modelagem/casos_de_uso.md
    - Validação dos Casos de Uso: modelagem/validacao.md
    - Especificação Suplementar: modelagem/especificacao_suplementar.md
    - Léxicos: modelagem/lexicos.md
    - Ágil:
      - Backlog: modelagem/agil/backlog.md
      - Histórias de Usuário: modelagem/agil/historias_de_usuario.md
      - NFR Framework: modelagem/agil/nfr-framework.md
  - Verificação:
    - Grupo + 1:
      - Elicitação:
        - Personas: verificacao/grupo+1/elicitacao/personas.md
        - Elicitação:
          - Análise de Documentos: verificacao/grupo+1/elicitacao/analise-documentos.md
          - Storytelling: verificacao/grupo+1/elicitacao/storytelling.md 
          - Brainstorming: verificacao/grupo+1/elicitacao/brainstorming.md           
        - Priorização:
          - First Things First: verificacao/grupo+1/elicitacao/firstThingsFirst.md
          - MoSCoW: verificacao/grupo+1/elicitacao/moscow.md
      - Modelagem:
        - Cenários: verificacao/grupo+1/modelagem/cenarios.md
        - Casos de Uso: verificacao/grupo+1/template.md
        - Validação dos Casos de Uso: verificacao/grupo+1/template.md
        - Especificação Suplementar: verificacao/grupo+1/modelagem/especificacao_suplementar.md
        - Léxicos: verificacao/grupo+1/template.md
        - Ágil:
          - Backlog: verificacao/grupo+1/modelagem/agil/backlog.md
          - Histórias de Usuário: verificacao/grupo+1/modelagem/agil/historias_de_usuario.md
          - NFR Framework: verificacao/grupo+1/template.md
    - Grupo:
      - Divisão de Tarefas: verificacao/grupo/template.md
      
extra_css:
  - stylesheets/extra.css
theme:
  language: pt-BR
  name: material
  favicon: assets/correios_icon.svg
  logo: assets/correios-icon-black.svg
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme : default
      primary: amber
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Mudar o modo clar/escuro 

    - scheme: slate
      primary: amber
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mudar o modo clar/escuro


