site_name: Serasa Consulta CPF e Socore
nav: 
  - Home: index.md
  - Sobre: sobre.md
  - Contato: contato.md
  - Atas:
    - Reunião 1: atas/ata1.md
theme:
  name: material
  logo: assets/serasa_logo_01.jpg
  features:
    - navigation.tabs
  palette:
    - scheme : default
      primary: pink
      toggle:
        icon: material/toggle-switch
        name: Mudar o modo clar/escuro 
    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mudar o modo clar/escuro


